version: "3"
services:
  db:
    image: postgres
    volumes:
      - /tmp/data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    # user is root
  # Database management in a single PHP file.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080